### ISSUE TITLE
Support PKCS7-wrapped keys

### ISSUE THREAD

**Issue by uhoreg** [muchlearning/cert-chain-resolver-py#2]
Some certificates (notably the root certificate that cross-signs the Let's Encrypt intermediate) are wrapped in PKCS7.  The script should extract the certificate from the PKCS7 wrapper.

**Comment by olmari** [comment]
Both 'issues' are important to resolve. While I don't have expertise to code such deep stuff, I am willing to comment and especially test this stuff, as this is exactly what I need in many situations... While bash/sh is  mostly what I need, I can get away with python too... Ready link for obsoleted sh script, if it could give at least pointers too https://github.com/zakjan/cert-chain-resolver/blob/shell/src/cert-chain-resolver.sh
